arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false # Explicitly disable synthetic package
untranslated-messages-file: lib/l10n/untranslated_messages.txt # Generate a report
nullable-getter: false # Optional: Ensures getters are non-nullable