import 'package:nightview/generated/l10n.dart';
import 'package:nightview/main.dart';

class NotificationMessage {
  static List<String> getNotificationMessages() {
    final S s = S.of(ourNavigatorKey.currentContext!);
    return [
      s.ready_to_conquer_dancefloor,
      s.plans_for_adventure,
      s.let_make_trouble,
      s.wild_night,
      s.let_loose,
      s.show_best_moves,
      s.make_city_safe,
      s.good_bartender,
      s.be_my_date,
      s.waste_youth,
      s.light_up_dancefloor,
      s.create_memories,
      s.max_gas,
      s.make_night_unforgettable,
      s.take_city_with_style,
      s.night_of_laughter_and_dance,
      s.conquer_city,
      s.make_own_party,
      s.let_go_of_inhibitions,
      s.night_adventure,
      s.make_streets_safe,
      s.create_party_vibe,
      s.make_night_special,
      s.live_life_to_fullest,
      s.party_like_never_before,
      s.take_nightlife_by_storm,
      s.make_night_unforgettable,
      s.dancefloor_as_stage,
      s.light_up_city,
      s.go_wild_on_dancefloor,
      s.be_center_of_party,
      s.night_full_of_fun,
      s.take_city_by_storm,
      s.create_wild_memories,
      s.party_without_equal,
      s.fire_up_dancefloor,

      s.adventure_in_nightlife,
      s.conquer_nightlife,
      s.play_rockstars,
      s.dance_with_two_left_feet,
      s.epic_snapchat_stories,
      s.crazy_party_animal,
      s.legendary_missteps,
      s.make_new_friends,
      s.trip_to_party_league,
      s.going_out_tonight,
      s.shall_we,
      s.fire_it_up,
      s.drinking,
      s.going_out,
      s.club,
      s.create_ravage,
      s.create_festive_chaos,
      s.shake_up_city,
      s.time_for_trouble,
      s.part_of_nightlife,
      s.plans_for_evening,
      s.ready_for_city_trip,
// =======
// class NotificationMessage {
//   static List<String> getNotificationMessages() {
//     return [
//       "Er du klar til at erobre dansegulvet i nat?",
//       "Har du planer om at tage på eventyr i byen i aften?",
//       "Skal vi ud og lave ballade i nat?",
//       "Bliver det en af de vilde aftener i byen i aften?",
//       "Er det en af de aftener, hvor vi slår os løs?",
//       "Skal vi ud og vise vores bedste moves i aften?",
//       "Er du på vej ud for at gøre byen usikker i nat?",
//       "Jeg kender en rigtig god bartender. Skal vi tage ud og få ham til at lave nogle specielle drinks til os?",
//       "Vil du være min date i aften og lade mig vise dig hvordan man har det sjovt?",
//       "Hvad siger du til at vi spilder ungdommen lidt i aften og ser hvor det bringer os hen?",
//       "Er du klar til at lyse dansegulvet op i aften?",
//       "Har du planer om at skabe minder i byen i nat?",
//       "Er det en af de aftener, hvor vi giver den max gas?",
//       "Skal vi ud og gøre natten vild og uforglemmelig?",
//       "Er du parat til at indtage byen med stil?",
//       "Bliver det en nat med masser af latter og dans?",
//       "Er du klar til at erobre byen og have det sjovt?",
//       "Skal vi ud og gøre natten til vores egen fest?",
//       "Er det en af de aftener, hvor vi slipper alle hæmninger?",
//       "Har du tænkt dig at tage på natteeventyr med os i aften?",
//       "Er det i aften, vi gør gaderne usikre?",
//       "Skal vi ud og skabe feststemning i nat?",
//       "Er du klar til at gøre natten til noget særligt?",
//       "Bliver det en af de aftener, hvor vi lever livet fuldt ud?",
//       "Skal vi ud og feste som aldrig før i nat?",
//       "Er du klar til at indtage nattelivet med os?",
//       "Har du tænkt dig at gøre natten vild og uforglemmelig?",
//       "Er du klar til at gøre dansegulvet til din scene i aften?",
//       "Skal vi ud og få byen til at lyse op i nat?",
//       "Er det i aften, vi går amok på dansegulvet?",
//       "Har du tænkt dig at være festens midtpunkt i nat?",
//       "Er du parat til en nat fyldt med grin og gode vibes?",
//       "Er du klar til at tage byen med storm i aften?",
//       "Er du klar til at skabe vilde minder i nat?",
//       "Er du parat til at gøre natten til en fest uden lige?",
//       "Skal vi ud og fyre den af på dansegulvet?",
//       "Er du klar til at gøre byen usikker med os i nat?",
//       "Har du planer om at tage på eventyr i nattelivet?",
//       "Skal vi ud og erobre nattelivet i aften?",
//       "Skal vi ud og lege rockstjerner i nat?",
//       "Er du klar til at danse, som om vi har to venstre fødder?",
//       "Er det i aften, vi laver nogle episke Snapchat-historier?",
//       "Er du klar til at være byens skøreste festabe i nat?",
//       "Skal vi ud og lave nogle legendariske fejltrin på dansegulvet?",
//       "Skal vi ud og se, hvor mange nye venner vi kan få i nat?",
//       "Er du klar til at tage en tur i festligaen i nat?",
//       "Ud i aften?",
//       "Skal vi?",
//       "Ud og fyre den af?",
//       "Druk?",
//       "Skal vi ud?",
//       "Klubben?",
//       "Er du klar til at skabe ravage i byen i aften?",
//       "Skal vi ud og skabe lidt festlig uro i byen?",
//       "Skal vi ud og ryste byen op?",
//       "Er det tid til at lave noget ballade i nat?",
//       "Bliver du en del af nattelivet i dag?",
//       "Har du planer om at gå ud i aften?",
//       "Er du klar til en bytur i dag?",
// >>>>>>> origin/Version_1_iOS
    ];
//   }
  }
}
