import 'package:nightview/generated/l10n.dart';
import 'package:nightview/main.dart';

class NotificationMessage {
  static List<String> getNotificationMessages() {
    final S s = S.of(ourNavigatorKey.currentContext!);
    return [
      s.ready_to_conquer_dancefloor,
      s.plans_for_adventure,
      s.let_make_trouble,
      s.wild_night,
      s.let_loose,
      s.show_best_moves,
      s.make_city_safe,
      s.good_bartender,
      s.be_my_date,
      s.waste_youth,
      s.light_up_dancefloor,
      s.create_memories,
      s.max_gas,
      s.make_night_unforgettable,
      s.take_city_with_style,
      s.night_of_laughter_and_dance,
      s.conquer_city,
      s.make_own_party,
      s.let_go_of_inhibitions,
      s.night_adventure,
      s.make_streets_safe,
      s.create_party_vibe,
      s.make_night_special,
      s.live_life_to_fullest,
      s.party_like_never_before,
      s.take_nightlife_by_storm,
      s.make_night_unforgettable_2,
      s.dancefloor_as_stage,
      s.light_up_city,
      s.go_wild_on_dancefloor,
      s.be_center_of_party,
      s.night_full_of_fun,
      s.take_city_by_storm,
      s.create_wild_memories,
      s.party_without_equal,
      s.fire_up_dancefloor,
      s.make_city_safe_2,
      s.adventure_in_nightlife,
      s.conquer_nightlife,
      s.play_rockstars,
      s.dance_with_two_left_feet,
      s.epic_snapchat_stories,
      s.crazy_party_animal,
      s.legendary_missteps,
      s.make_new_friends,
      s.trip_to_party_league,
      s.going_out_tonight,
      s.shall_we,
      s.fire_it_up,
      s.drinking,
      s.going_out,
      s.club,
      s.create_ravage,
      s.create_festive_chaos,
      s.shake_up_city,
      s.time_for_trouble,
      s.part_of_nightlife,
      s.plans_for_evening,
      s.ready_for_city_trip,
    ];
  }
}
